### ISSUE TITLE
broken Windows build since a55140f63f

### ISSUE THREAD

**Issue by avih** [gwsw/less#690]
Commit a55140f63f broke windows build with:
```
os.c: In function 'iread':
os.c:372:19: error: 'tty' undeclared (first use in this function)
  372 |         if (fd != tty && n > 0)
      |                   ^~~
```

and current master is similarly broken with:
```
os.c: In function 'iread':
os.c:372:19: error: 'tty' undeclared (first use in this function)
  372 |         if (fd != tty && !any_data)
      |                   ^~~
```

I presume the issue is the removal of `#if USE_POLL` ?

**Comment by avih** [comment]
It would be useful to have CI builds which include windows/mingw, so that breakage is detected quite earlier.

The windows build has been broken for about 20 commits now (including at v687 and v688), and it's not the first time it happens, sometimes for many more commits, which makes it hard to bisect issues on windows - if the bisection process goes through a commit where the build was broken (which requires to backport patches in order to keep the bisection going - not fun).

Setting up CI builds should not be hard (likely at least linux/mingw, but possibly some BSD/OSX too), but I don't have experience with that...

Until/if windows CI is added, I think windows build should be tested at least before every new version - public or not, to ensure that at least every version also builds for windows.

**Comment by gwsw** [comment]
Fixed in 650b291efdd0562e7de29343b8fbd83a76453c8e.

I don't know anything about setting up github CI builds. I read a little of the documentation and found it more than I can digest right now, but I'll try to look at it sometime.

**Comment by avih** [comment]
> I don't know anything about setting up github CI builds.

As I said, it would be useful and definitely nice to have (not only for windows), but I don't think it's critical.

However, testing before at least every new version that it also builds on windows might be considered important, because history shows that on occasions it has been broken.

Searching the log for "windows build" yields about 10 results about build fixes (likely there are more which don't match exactly).

But there were no linux build breakage which I recall (of course, there might have been some which I didn't encounter).

FWIW, the previous big windows breakage duration I know of is v617..v630 (~ 150 commits) where `init_poll` is unresolved.

Prior to that, MSVC build (before the mingw makefile) was broken in v490..v511 (technically it was broken since v333 with `error(...)` on windows being called with wrong number of arguments, but the build itself is broken since v490 which switched to ANSI C function prototypes and exposed this issue, and fixed in v511).

These breakages, even if only for few commits at a time, are a major PITA when bisecting an issue, because a bisect process over any non-negligible set of commit is highly likely to bump into at least one of those while narrowing the offending commit.

And that's why I maintain my [multi-version makefile](https://github.com/avih/less/blob/avih/Makefile.avih) which applies all these fixes for the different breakages, so that it can be bisected relatively freely. That's the [new portion](https://github.com/avih/less/blob/b74b0ade970db717dd49012389b82c2edfe8d795/Makefile.avih#L372-L383) which fixes this breakage (with additional change at [.c.o:](https://github.com/avih/less/blob/b74b0ade970db717dd49012389b82c2edfe8d795/Makefile.avih#L222) which applies the OS_FIXUP value).

The aforementioned `init_poll` breakage fix is [here](https://github.com/avih/less/blob/b74b0ade970db717dd49012389b82c2edfe8d795/Makefile.avih#L363-L370), and the `error(...)` fix is [here](https://github.com/avih/less/blob/b74b0ade970db717dd49012389b82c2edfe8d795/Makefile.avih#L343-L345) and [here](https://github.com/avih/less/blob/b74b0ade970db717dd49012389b82c2edfe8d795/Makefile.avih#L444-L458), as well as several other fixups...

**Comment by avih** [comment]
Also, in case you were not aware or didn't recall, we did fix `Makefile.wng` to support cross compiling too (and parallel and/or incremental build), e.g. on linux, assuming you have mingw installed.

So booting a windows VM is not required to build less for windows (maybe not even to test it, if you have `wine`, but I didn't try it).

E.g. on my ubuntu, where the mingw gcc is `x86_64-w64-mingw32.static-gcc`, this completes in 2-3 seconds, and would have been enough to detect this breakage:
```sh
git clean -xfd  # remove all non-indexed files - ensure clean slate
make -f Makefile.wng SHELL=sh CC=x86_64-w64-mingw32.static-gcc -j12
```

So maybe you could just increase the windows builds frequency to detect such failures hopefully earlier, without much effort...

(my multi-version makefile similarly supports cross-build and parallel/incremental builds, with the same required SHELL and CC values set correctly at the `make` invocation).

**Comment by avih** [comment]
I see that this continues to be an issue (3 new commits broken on windows, which were actually important while bisecting it - see https://github.com/gwsw/less/issues/682#issuecomment-3628158994).

Would it help if I add something to `Makefile.wng` which would allow testing that it builds on windows out of tree - without touching any files in the tree, so that it doesn't interrupt the development process on unix/linux?

I imagine your (@gwsw) issue is that even with cross compiling, testing that it builds for windows still requires to clean the tree, which then requires to use `Makefile.aut` and `configure` to continue working on something, presumably on linux, and that's why windows builds are not tested more frequently?

If yes, then making such change to `Makefile.wng` (or some other procedure with the same effect) should allow 100% friction-less tests that it builds for windows too, right?

**Comment by gwsw** [comment]
The issue isn't really about cleaning the tree. I mostly do development on a Linux VM, and sometimes on a MacBook. After making a change and testing on Linux/MacOS, in order to then test on Windows, I need to identify which files have been changed, manually copy them to a Windows machine, do the compile/testing there, manually copy any files that get changed on Windows back to Linux, retest there, and then commit. It's a cumbersome process that I frequently either forget to do or just skip because I think that a particular change isn't likely to affect Windows differently. I guess the most useful thing I could do to streamline it would be to set up some kind of cross compilation environment so I could at least do a Windows compile in the Linux filesystem without needing to copy to a different machine. I'm not sure what the best way would be to do that.

**Comment by avih** [comment]
By what you say, I think i've been spot on in my assessment of what makes it harder for you to test at the very least that it builds for windows.

And build-breakage is by far the biggest issue, because that's what breaking the bisect once an issue is identified - possibly some time after it was actually introduced.

So yes, cross compile is definitely an option to test that it still builds, as I stated above, and additionally, I think that not breaking the workflow does have value (make some linux change, test on linux, then test that it builds for windows but without touching the current tree).

Most linux/BSD distros do have a mingw package, and testing that it builds is a single `make` away if the the tree is already clean, or using some script which doesn't even disturb the current tree, e.g. this `winbuild` script in your PATH:

```sh
#!/bin/sh

# cross-build less-for-windows (mingw), without disturbing current tree state.
# expects (and checks) CWD to be a "less" source-dir.
# Creates and populates $BUILDDIR (winbuild.tmp) with sources, and mingw-build.

[ -r ./less.h ] || { >&2 echo "$0: abort: not in 'less' source dir"; exit 1; }

# automatically find the first mingw gcc, or fallback to a generic mingw name.
CC=$(IFS=:; find $PATH -name '*mingw*-gcc' | head -n1)
[ "$CC" ] || CC=x86_64-w64-mingw32-gcc

BUILDDIR=winbuild.tmp
GENERATED="defines.h funcs.h help.c"
MAKEARGS="CC=$CC SHELL=sh XCFLAGS=-O0 -j12"

rm -rf $BUILDDIR &&
mkdir $BUILDDIR &&
cp *.c *.h *.uni mkhelp* defines.wn less.hlp $BUILDDIR/ &&
cd $BUILDDIR &&
rm -f $GENERATED &&
make -f ../Makefile.wng $MAKEARGS "$@"
```

Note that currently the `XCFLAGS=-O0` arg has no effect in master (to speedup the build while testing), but in my `Makefile.wng` it does have an effect, because I have these lines, which I do want to add also to `Makefile.wng` in master (feel free to add it yourself):
```diff
diff --git a/Makefile.wng b/Makefile.wng
index 4d61b40..0a81e68 100644
--- a/Makefile.wng
+++ b/Makefile.wng
@@ -98,6 +98,14 @@ endif

 LIBS += -lshell32

+CFLAGS += ${XCFLAGS}
+LDFLAGS += ${XLDFLAGS}
+LIBS += ${XLDLIBS}
+
 #### End of system configuration section. ####

 # This rule allows us to supply the necessary -D options
```

So you can run this script on linux just to confirm that it still also builds for windows, while developing for linux/unix, which takes barely few secs, and right away keep working on linux - with the source tree kept unmodified since the last (linux) build...

And, if you have `wine` installed, you can even perform some actual windows tests without leaving your linux shell (that's not a real replacement to actually test on windows, but surely it can detect at least some breakages early).

**Comment by avih** [comment]
@gwsw Can you confirm this script works for you to test that it builds for windows without disturbing the current tree?

**Comment by gwsw** [comment]
Yes, I installed mingw and confirmed that the script works for me. I will try to at least do a mingw build before committing code changes going forward.

**Comment by avih** [comment]
Appreciated.
